-- V53: KATOTTH locality seed (Phase 10.2)
--
-- Permanent, environment-agnostic reference-data seed for the Phase 10.1
-- taxonomy (oblasts / cities / city_districts, migration V52). Replays
-- byte-identically on every environment (single Neon dev DB, future dev
-- instance, future prod). Contains ONLY controlled KATOTTH reference data:
-- zero environment-specific fixes, zero references to legacy free-text
-- users/salons location columns (legacy cleanup is Phase 10.3, dev-only and
-- explicitly out of the permanent migration chain).
--
-- Source: official Ukrainian KATOTTH classifier
--   Наказ Міністерства розвитку громад та територій України від 02.07.2025 № 1065 «Про внесення змін до Кодифікатора адміністративно-територіальних одиниць та територій територіальних громад»
--   valid_on: 2025-05-16
-- Generated by docs/backend-phases/data/extract_katotth_seed.py from the
-- pinned snapshot docs/backend-phases/data/katottg-2025-05-16.json. The
-- authoritative artefact is THIS .sql file; the script + snapshot exist for
-- audit/reproducibility (Phase 10.2 Step 0).
--
-- Occupied / non-serviceable territory filter (Phase 10.2 Step 1) — applied
-- as a DATA filter by oblast KATOTTH code, never a schema change. Excluded
-- (and all subordinate cities/districts):
--   AR Crimea     UA01000000000013043
--   Donetsk obl.  UA14000000000091971
--   Luhansk obl.  UA44000000000018893
--   Sevastopol    UA85000000000065278
-- Re-including a liberated territory later is a single forward-only seed
-- migration adding the oblast row(s) + its cities/districts. The per-table
-- UNIQUE katotth_code constraints from V52 keep that conflict-free; this
-- seed therefore uses NO "ON CONFLICT" (the seed must be clean, not masked).
--
-- Kyiv is a special-status city (KATOTTH category K): it is BOTH an
-- oblast-equivalent and a city. It is inserted as one oblasts row and one
-- cities row sharing KATOTTH code UA80000000000093317. The UNIQUE constraint on
-- katotth_code is per-table (uq_oblasts_katotth_code / uq_cities_katotth_code),
-- so the same code in both tables is valid and faithful to the classifier.
--
-- Row-count sanity bounds (authoritative, from the pinned snapshot):
--   oblasts        = 23   (22 category-O oblasts + Kyiv special-status city;
--                          Crimea/Donetsk/Luhansk oblasts + Sevastopol excluded)
--   cities         = 356  (355 category-M cities + Kyiv)
--   city_districts = 76   category-B urban districts across 17 cities
--
-- Category-B urban districts per city (authoritative — from official KATOTTH;
-- supersedes the earlier hand-estimated 58/9 figure in
-- docs/backend-phases/data/katotth-seed-sourcing.md, which has been corrected):
--   Kyiv 10, Kharkiv 9, Dnipro 8, Zaporizhzhia 7, Kryvyi Rih 7, Lviv 6,
--   Mykolaiv 4, Odesa 4, Kamianske 3, Poltava 3, Kherson 3, Zhytomyr 2,
--   Kropyvnytskyi 2, Kremenchuk 2, Sumy 2, Cherkasy 2, Chernihiv 2.
--   (Vinnytsia has NO category-B districts in the official classifier.)
--
-- Insert order: oblasts -> cities (oblast_id resolved via subquery on
-- oblasts.katotth_code) -> city_districts (city_id resolved via subquery on
-- cities.katotth_code). No hardcoded UUIDs — gen_random_uuid() fills id.

-- ============================================================================
-- OBLASTS (23)
-- ============================================================================
INSERT INTO oblasts (katotth_code, name_uk, name_en) VALUES ('UA05000000000010236', 'Вінницька', 'Vinnytska');
INSERT INTO oblasts (katotth_code, name_uk, name_en) VALUES ('UA07000000000024379', 'Волинська', 'Volynska');
INSERT INTO oblasts (katotth_code, name_uk, name_en) VALUES ('UA12000000000090473', 'Дніпропетровська', 'Dnipropetrovska');
INSERT INTO oblasts (katotth_code, name_uk, name_en) VALUES ('UA18000000000041385', 'Житомирська', 'Zhytomyrska');
INSERT INTO oblasts (katotth_code, name_uk, name_en) VALUES ('UA21000000000011690', 'Закарпатська', 'Zakarpatska');
INSERT INTO oblasts (katotth_code, name_uk, name_en) VALUES ('UA23000000000064947', 'Запорізька', 'Zaporizka');
INSERT INTO oblasts (katotth_code, name_uk, name_en) VALUES ('UA26000000000069363', 'Івано-Франківська', 'Ivano-Frankivska');
INSERT INTO oblasts (katotth_code, name_uk, name_en) VALUES ('UA32000000000030281', 'Київська', 'Kyivska');
INSERT INTO oblasts (katotth_code, name_uk, name_en) VALUES ('UA35000000000016081', 'Кіровоградська', 'Kirovohradska');
INSERT INTO oblasts (katotth_code, name_uk, name_en) VALUES ('UA46000000000026241', 'Львівська', 'Lvivska');
INSERT INTO oblasts (katotth_code, name_uk, name_en) VALUES ('UA48000000000039575', 'Миколаївська', 'Mykolaivska');
INSERT INTO oblasts (katotth_code, name_uk, name_en) VALUES ('UA51000000000030770', 'Одеська', 'Odeska');
INSERT INTO oblasts (katotth_code, name_uk, name_en) VALUES ('UA53000000000028050', 'Полтавська', 'Poltavska');
INSERT INTO oblasts (katotth_code, name_uk, name_en) VALUES ('UA56000000000066151', 'Рівненська', 'Rivnenska');
INSERT INTO oblasts (katotth_code, name_uk, name_en) VALUES ('UA59000000000057109', 'Сумська', 'Sumska');
INSERT INTO oblasts (katotth_code, name_uk, name_en) VALUES ('UA61000000000060328', 'Тернопільська', 'Ternopilska');
INSERT INTO oblasts (katotth_code, name_uk, name_en) VALUES ('UA63000000000041885', 'Харківська', 'Kharkivska');
INSERT INTO oblasts (katotth_code, name_uk, name_en) VALUES ('UA65000000000030969', 'Херсонська', 'Khersonska');
INSERT INTO oblasts (katotth_code, name_uk, name_en) VALUES ('UA68000000000099709', 'Хмельницька', 'Khmelnytska');
INSERT INTO oblasts (katotth_code, name_uk, name_en) VALUES ('UA71000000000010357', 'Черкаська', 'Cherkaska');
INSERT INTO oblasts (katotth_code, name_uk, name_en) VALUES ('UA73000000000044923', 'Чернівецька', 'Chernivetska');
INSERT INTO oblasts (katotth_code, name_uk, name_en) VALUES ('UA74000000000025378', 'Чернігівська', 'Chernihivska');
INSERT INTO oblasts (katotth_code, name_uk, name_en) VALUES ('UA80000000000093317', 'Київ', 'Kyiv');

-- ============================================================================
-- CITIES (356) — oblast_id resolved by oblast KATOTTH code
-- ============================================================================
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA05020030010063857', 'Вінниця', 'Vinnytsia'
FROM oblasts o WHERE o.katotth_code = 'UA05000000000010236';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA05020070010053570', 'Гнівань', 'Hnivan'
FROM oblasts o WHERE o.katotth_code = 'UA05000000000010236';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA05020090010088788', 'Іллінці', 'Illintsi'
FROM oblasts o WHERE o.katotth_code = 'UA05000000000010236';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA05020110010028819', 'Липовець', 'Lypovets'
FROM oblasts o WHERE o.katotth_code = 'UA05000000000010236';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA05020170010087489', 'Немирів', 'Nemyriv'
FROM oblasts o WHERE o.katotth_code = 'UA05000000000010236';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA05020210010023649', 'Погребище', 'Pohrebyshche'
FROM oblasts o WHERE o.katotth_code = 'UA05000000000010236';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA05040010010024726', 'Бершадь', 'Bershad'
FROM oblasts o WHERE o.katotth_code = 'UA05000000000010236';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA05040030010071792', 'Гайсин', 'Haisyn'
FROM oblasts o WHERE o.katotth_code = 'UA05000000000010236';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA05040130010040578', 'Ладижин', 'Ladyzhyn'
FROM oblasts o WHERE o.katotth_code = 'UA05000000000010236';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA05060010010059821', 'Бар', 'Bar'
FROM oblasts o WHERE o.katotth_code = 'UA05000000000010236';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA05060050010030599', 'Жмеринка', 'Zhmerynka'
FROM oblasts o WHERE o.katotth_code = 'UA05000000000010236';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA05060150010066273', 'Шаргород', 'Sharhorod'
FROM oblasts o WHERE o.katotth_code = 'UA05000000000010236';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA05080050010069812', 'Могилів-Подільський', 'Mohyliv-Podilskyi'
FROM oblasts o WHERE o.katotth_code = 'UA05000000000010236';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA05080110010069634', 'Ямпіль', 'Yampil'
FROM oblasts o WHERE o.katotth_code = 'UA05000000000010236';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA05100150010035552', 'Тульчин', 'Tulchyn'
FROM oblasts o WHERE o.katotth_code = 'UA05000000000010236';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA05120070010068103', 'Калинівка', 'Kalynivka'
FROM oblasts o WHERE o.katotth_code = 'UA05000000000010236';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA05120090010077573', 'Козятин', 'Koziatyn'
FROM oblasts o WHERE o.katotth_code = 'UA05000000000010236';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA05120170010081140', 'Хмільник', 'Khmilnyk'
FROM oblasts o WHERE o.katotth_code = 'UA05000000000010236';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA07020010010041660', 'Володимир', 'Volodymyr'
FROM oblasts o WHERE o.katotth_code = 'UA07000000000024379';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA07020130010041880', 'Нововолинськ', 'Novovolynsk'
FROM oblasts o WHERE o.katotth_code = 'UA07000000000024379';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA07020210010031545', 'Устилуг', 'Ustyluh'
FROM oblasts o WHERE o.katotth_code = 'UA07000000000024379';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA07040010010025318', 'Камінь-Каширський', 'Kamin-Kashyrskyi'
FROM oblasts o WHERE o.katotth_code = 'UA07000000000024379';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA07060190010068509', 'Ковель', 'Kovel'
FROM oblasts o WHERE o.katotth_code = 'UA07000000000024379';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA07060270010018151', 'Любомль', 'Liuboml'
FROM oblasts o WHERE o.katotth_code = 'UA07000000000024379';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA07080010010043939', 'Берестечко', 'Berestechko'
FROM oblasts o WHERE o.katotth_code = 'UA07000000000024379';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA07080070010026475', 'Горохів', 'Horokhiv'
FROM oblasts o WHERE o.katotth_code = 'UA07000000000024379';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA07080110010029699', 'Ківерці', 'Kivertsi'
FROM oblasts o WHERE o.katotth_code = 'UA07000000000024379';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA07080170010083384', 'Луцьк', 'Lutsk'
FROM oblasts o WHERE o.katotth_code = 'UA07000000000024379';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA07080210010079720', 'Олика', 'Olyka'
FROM oblasts o WHERE o.katotth_code = 'UA07000000000024379';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA07080250010017534', 'Рожище', 'Rozhyshche'
FROM oblasts o WHERE o.katotth_code = 'UA07000000000024379';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA12020010010037010', 'Дніпро', 'Dnipro'
FROM oblasts o WHERE o.katotth_code = 'UA12000000000090473';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA12020210010051215', 'Підгородне', 'Pidhorodne'
FROM oblasts o WHERE o.katotth_code = 'UA12000000000090473';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA12040030010058766', 'Верхівцеве', 'Verkhivtseve'
FROM oblasts o WHERE o.katotth_code = 'UA12000000000090473';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA12040050010019298', 'Верхньодніпровськ', 'Verkhnodniprovsk'
FROM oblasts o WHERE o.katotth_code = 'UA12000000000090473';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA12040090010047409', 'Вільногірськ', 'Vilnohirsk'
FROM oblasts o WHERE o.katotth_code = 'UA12000000000090473';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA12040110010051141', 'Жовті Води', 'Zhovti Vody'
FROM oblasts o WHERE o.katotth_code = 'UA12000000000090473';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA12040150010056523', 'Кам’янське', 'Kamianske'
FROM oblasts o WHERE o.katotth_code = 'UA12000000000090473';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA12040210010024143', 'П’ятихатки', 'Piatykhatky'
FROM oblasts o WHERE o.katotth_code = 'UA12000000000090473';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA12060010010033935', 'Апостолове', 'Apostolove'
FROM oblasts o WHERE o.katotth_code = 'UA12000000000090473';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA12060130010067974', 'Зеленодольськ', 'Zelenodolsk'
FROM oblasts o WHERE o.katotth_code = 'UA12000000000090473';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA12060170010065850', 'Кривий Ріг', 'Kryvyi Rih'
FROM oblasts o WHERE o.katotth_code = 'UA12000000000090473';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA12080010010085669', 'Марганець', 'Marhanets'
FROM oblasts o WHERE o.katotth_code = 'UA12000000000090473';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA12080050010010114', 'Нікополь', 'Nikopol'
FROM oblasts o WHERE o.katotth_code = 'UA12000000000090473';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA12080090010010311', 'Покров', 'Pokrov'
FROM oblasts o WHERE o.katotth_code = 'UA12000000000090473';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA12100070010038698', 'Самар', 'Samar'
FROM oblasts o WHERE o.katotth_code = 'UA12000000000090473';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA12100090010016421', 'Перещепине', 'Pereshchepyne'
FROM oblasts o WHERE o.katotth_code = 'UA12000000000090473';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA12120070010055676', 'Павлоград', 'Pavlohrad'
FROM oblasts o WHERE o.katotth_code = 'UA12000000000090473';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA12120090010057273', 'Тернівка', 'Ternivka'
FROM oblasts o WHERE o.katotth_code = 'UA12000000000090473';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA12140210010011011', 'Шахтарське', 'Shakhtarske'
FROM oblasts o WHERE o.katotth_code = 'UA12000000000090473';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA12140310010049426', 'Синельникове', 'Synelnykove'
FROM oblasts o WHERE o.katotth_code = 'UA12000000000090473';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA18020010010097402', 'Андрушівка', 'Andrushivka'
FROM oblasts o WHERE o.katotth_code = 'UA18000000000041385';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA18020030010047029', 'Бердичів', 'Berdychiv'
FROM oblasts o WHERE o.katotth_code = 'UA18000000000041385';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA18040190010057814', 'Житомир', 'Zhytomyr'
FROM oblasts o WHERE o.katotth_code = 'UA18000000000041385';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA18040250010085012', 'Коростишів', 'Korostyshiv'
FROM oblasts o WHERE o.katotth_code = 'UA18000000000041385';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA18040450010049683', 'Радомишль', 'Radomyshl'
FROM oblasts o WHERE o.katotth_code = 'UA18000000000041385';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA18040610010066897', 'Чуднів', 'Chudniv'
FROM oblasts o WHERE o.katotth_code = 'UA18000000000041385';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA18060090010074365', 'Коростень', 'Korosten'
FROM oblasts o WHERE o.katotth_code = 'UA18000000000041385';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA18060130010010134', 'Малин', 'Malyn'
FROM oblasts o WHERE o.katotth_code = 'UA18000000000041385';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA18060170010010060', 'Овруч', 'Ovruch'
FROM oblasts o WHERE o.katotth_code = 'UA18000000000041385';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA18060190010064821', 'Олевськ', 'Olevsk'
FROM oblasts o WHERE o.katotth_code = 'UA18000000000041385';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA18080010010059187', 'Баранівка', 'Baranivka'
FROM oblasts o WHERE o.katotth_code = 'UA18000000000041385';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA18080150010017476', 'Звягель', 'Zviahel'
FROM oblasts o WHERE o.katotth_code = 'UA18000000000041385';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA21020030010083215', 'Берегове', 'Berehove'
FROM oblasts o WHERE o.katotth_code = 'UA21000000000011690';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA21020110010043238', 'Виноградів', 'Vynohradiv'
FROM oblasts o WHERE o.katotth_code = 'UA21000000000011690';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA21040150010056148', 'Мукачево', 'Mukachevo'
FROM oblasts o WHERE o.katotth_code = 'UA21000000000011690';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA21040230010045142', 'Свалява', 'Svaliava'
FROM oblasts o WHERE o.katotth_code = 'UA21000000000011690';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA21060050010040895', 'Рахів', 'Rakhiv'
FROM oblasts o WHERE o.katotth_code = 'UA21000000000011690';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA21080150010051267', 'Тячів', 'Tiachiv'
FROM oblasts o WHERE o.katotth_code = 'UA21000000000011690';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA21100130010027304', 'Перечин', 'Perechyn'
FROM oblasts o WHERE o.katotth_code = 'UA21000000000011690';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA21100230010016545', 'Ужгород', 'Uzhhorod'
FROM oblasts o WHERE o.katotth_code = 'UA21000000000011690';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA21100270010071297', 'Чоп', 'Chop'
FROM oblasts o WHERE o.katotth_code = 'UA21000000000011690';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA21120130010065349', 'Іршава', 'Irshava'
FROM oblasts o WHERE o.katotth_code = 'UA21000000000011690';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA21120250010053148', 'Хуст', 'Khust'
FROM oblasts o WHERE o.katotth_code = 'UA21000000000011690';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA23020050010019935', 'Бердянськ', 'Berdiansk'
FROM oblasts o WHERE o.katotth_code = 'UA23000000000064947';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA23020130010076068', 'Приморськ', 'Prymorsk'
FROM oblasts o WHERE o.katotth_code = 'UA23000000000064947';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA23040030010016724', 'Василівка', 'Vasylivka'
FROM oblasts o WHERE o.katotth_code = 'UA23000000000064947';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA23040090010050034', 'Дніпрорудне', 'Dniprorudne'
FROM oblasts o WHERE o.katotth_code = 'UA23000000000064947';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA23040110010044100', 'Енергодар', 'Enerhodar'
FROM oblasts o WHERE o.katotth_code = 'UA23000000000064947';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA23040130010014334', 'Кам’янка-Дніпровська', 'Kamianka-Dniprovska'
FROM oblasts o WHERE o.katotth_code = 'UA23000000000064947';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA23060030010056906', 'Вільнянськ', 'Vilniansk'
FROM oblasts o WHERE o.katotth_code = 'UA23000000000064947';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA23060070010069526', 'Запоріжжя', 'Zaporizhzhia'
FROM oblasts o WHERE o.katotth_code = 'UA23000000000064947';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA23080070010092407', 'Мелітополь', 'Melitopol'
FROM oblasts o WHERE o.katotth_code = 'UA23000000000064947';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA23100070010036682', 'Гуляйполе', 'Huliaipole'
FROM oblasts o WHERE o.katotth_code = 'UA23000000000064947';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA23100150010091297', 'Молочанськ', 'Molochansk'
FROM oblasts o WHERE o.katotth_code = 'UA23000000000064947';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA23100170010023304', 'Оріхів', 'Orikhiv'
FROM oblasts o WHERE o.katotth_code = 'UA23000000000064947';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA23100190010032690', 'Пологи', 'Polohy'
FROM oblasts o WHERE o.katotth_code = 'UA23000000000064947';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA23100270010029314', 'Токмак', 'Tokmak'
FROM oblasts o WHERE o.katotth_code = 'UA23000000000064947';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA26040070010092973', 'Бурштин', 'Burshtyn'
FROM oblasts o WHERE o.katotth_code = 'UA26000000000069363';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA26040090010078723', 'Галич', 'Halych'
FROM oblasts o WHERE o.katotth_code = 'UA26000000000069363';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA26040190010045761', 'Івано-Франківськ', 'Ivano-Frankivsk'
FROM oblasts o WHERE o.katotth_code = 'UA26000000000069363';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA26040270010067876', 'Рогатин', 'Rohatyn'
FROM oblasts o WHERE o.katotth_code = 'UA26000000000069363';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA26040330010091232', 'Тисмениця', 'Tysmenytsia'
FROM oblasts o WHERE o.katotth_code = 'UA26000000000069363';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA26040350010070754', 'Тлумач', 'Tlumach'
FROM oblasts o WHERE o.katotth_code = 'UA26000000000069363';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA26060010010092713', 'Болехів', 'Bolekhiv'
FROM oblasts o WHERE o.katotth_code = 'UA26000000000069363';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA26060130010099427', 'Долина', 'Dolyna'
FROM oblasts o WHERE o.katotth_code = 'UA26000000000069363';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA26060170010082672', 'Калуш', 'Kalush'
FROM oblasts o WHERE o.katotth_code = 'UA26000000000069363';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA26080030010035324', 'Городенка', 'Horodenka'
FROM oblasts o WHERE o.katotth_code = 'UA26000000000069363';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA26080070010075786', 'Коломия', 'Kolomyia'
FROM oblasts o WHERE o.katotth_code = 'UA26000000000069363';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA26080230010020173', 'Снятин', 'Sniatyn'
FROM oblasts o WHERE o.katotth_code = 'UA26000000000069363';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA26100010010026473', 'Косів', 'Kosiv'
FROM oblasts o WHERE o.katotth_code = 'UA26000000000069363';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA26120070010010041', 'Надвірна', 'Nadvirna'
FROM oblasts o WHERE o.katotth_code = 'UA26000000000069363';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA26120150010047425', 'Яремче', 'Yaremche'
FROM oblasts o WHERE o.katotth_code = 'UA26000000000069363';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32000000010085013', 'Прип’ять', 'Prypiat'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32000000020050699', 'Чорнобиль', 'Chornobyl'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32020010010081183', 'Біла Церква', 'Bila Tserkva'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32020150010094707', 'Сквира', 'Skvyra'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32020190010060417', 'Тараща', 'Tarashcha'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32020210010016577', 'Тетіїв', 'Tetiiv'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32020230010055093', 'Узин', 'Uzyn'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32040010010093209', 'Бориспіль', 'Boryspil'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32040110010043320', 'Переяслав', 'Pereiaslav'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32040210010094429', 'Яготин', 'Yahotyn'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32060030010087257', 'Березань', 'Berezan'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32060050010081797', 'Бровари', 'Brovary'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32080070010087821', 'Буча', 'Bucha'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32080090010037585', 'Вишневе', 'Vyshneve'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32080150010049888', 'Ірпінь', 'Irpin'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32100010010059200', 'Вишгород', 'Vyshhorod'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32100130010084793', 'Славутич', 'Slavutych'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32120010010027554', 'Богуслав', 'Bohuslav'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32120030010069648', 'Васильків', 'Vasylkiv'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32120050010091788', 'Кагарлик', 'Kaharlyk'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32120090010020161', 'Миронівка', 'Myronivka'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32120110010071582', 'Обухів', 'Obukhiv'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32120130010035405', 'Ржищів', 'Rzhyshchiv'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32120150010043175', 'Українка', 'Ukrainka'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32140030010045925', 'Боярка', 'Boiarka'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA32140150010091295', 'Фастів', 'Fastiv'
FROM oblasts o WHERE o.katotth_code = 'UA32000000000030281';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA35020010010060566', 'Благовіщенське', 'Blahovishchenske'
FROM oblasts o WHERE o.katotth_code = 'UA35000000000016081';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA35020050010071459', 'Гайворон', 'Haivoron'
FROM oblasts o WHERE o.katotth_code = 'UA35000000000016081';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA35040030010012943', 'Бобринець', 'Bobrynets'
FROM oblasts o WHERE o.katotth_code = 'UA35000000000016081';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA35040110010034377', 'Долинська', 'Dolynska'
FROM oblasts o WHERE o.katotth_code = 'UA35000000000016081';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA35040130010097956', 'Знам’янка', 'Znamianka'
FROM oblasts o WHERE o.katotth_code = 'UA35000000000016081';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA35040210010019355', 'Кропивницький', 'Kropyvnytskyi'
FROM oblasts o WHERE o.katotth_code = 'UA35000000000016081';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA35060090010061989', 'Мала Виска', 'Mala Vyska'
FROM oblasts o WHERE o.katotth_code = 'UA35000000000016081';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA35060130010042714', 'Новомиргород', 'Novomyrhorod'
FROM oblasts o WHERE o.katotth_code = 'UA35000000000016081';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA35060150010035817', 'Новоукраїнка', 'Novoukrainka'
FROM oblasts o WHERE o.katotth_code = 'UA35000000000016081';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA35060190010082095', 'Помічна', 'Pomichna'
FROM oblasts o WHERE o.katotth_code = 'UA35000000000016081';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA35080050010051027', 'Олександрія', 'Oleksandriia'
FROM oblasts o WHERE o.katotth_code = 'UA35000000000016081';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA35080170010073614', 'Світловодськ', 'Svitlovodsk'
FROM oblasts o WHERE o.katotth_code = 'UA35000000000016081';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46020010010087534', 'Борислав', 'Boryslav'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46020030010069501', 'Дрогобич', 'Drohobych'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46020030020056516', 'Стебник', 'Stebnyk'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46020090010062870', 'Трускавець', 'Truskavets'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46040010010077682', 'Броди', 'Brody'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46040030010088253', 'Буськ', 'Busk'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46040070010068975', 'Золочів', 'Zolochiv'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46060010010065439', 'Бібрка', 'Bibrka'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46060050010098239', 'Глиняни', 'Hlyniany'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46060070010047335', 'Городок', 'Horodok'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46060130010043364', 'Жовква', 'Zhovkva'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46060190010052224', 'Кам’янка-Бузька', 'Kamianka-Buzka'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46060210010034733', 'Комарно', 'Komarno'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46060250010015970', 'Львів', 'Lviv'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46060250020038547', 'Винники', 'Vynnyky'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46060250030012851', 'Дубляни', 'Dubliany'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46060330010045641', 'Перемишляни', 'Peremyshliany'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46060370010036941', 'Пустомити', 'Pustomyty'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46060390010035472', 'Рава-Руська', 'Rava-Ruska'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46080050010034058', 'Добромиль', 'Dobromyl'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46080070010059040', 'Новий Калинів', 'Novyi Kalyniv'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46080110010064338', 'Рудки', 'Rudky'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46080130010066889', 'Самбір', 'Sambir'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46080150010090008', 'Старий Самбір', 'Staryi Sambir'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46080190010014284', 'Турка', 'Turka'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46080210010061725', 'Хирів', 'Khyriv'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46100050010010600', 'Жидачів', 'Zhydachiv'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46100110010094231', 'Миколаїв', 'Mykolaiv'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46100130010043013', 'Моршин', 'Morshyn'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46100150010069811', 'Новий Розділ', 'Novyi Rozdil'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46100190010093837', 'Сколе', 'Skole'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46100230010074173', 'Стрий', 'Stryi'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46100270010046817', 'Ходорів', 'Khodoriv'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46120010010057892', 'Белз', 'Belz'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46120010020094201', 'Угнів', 'Uhniv'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46120030010063566', 'Великі Мости', 'Velyki Mosty'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46120090010078401', 'Радехів', 'Radekhiv'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46120110010087965', 'Сокаль', 'Sokal'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46120130010071117', 'Шептицький', 'Sheptytskyi'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46120130020045105', 'Соснівка', 'Sosnivka'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46140030010062678', 'Мостиська', 'Mostyska'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46140050010045115', 'Новояворівськ', 'Novoiavorivsk'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46140070010067363', 'Судова Вишня', 'Sudova Vyshnia'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA46140110010091191', 'Яворів', 'Yavoriv'
FROM oblasts o WHERE o.katotth_code = 'UA46000000000026241';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA48020010010072548', 'Баштанка', 'Bashtanka'
FROM oblasts o WHERE o.katotth_code = 'UA48000000000039575';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA48020150010063715', 'Новий Буг', 'Novyi Buh'
FROM oblasts o WHERE o.katotth_code = 'UA48000000000039575';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA48020190010089719', 'Снігурівка', 'Snihurivka'
FROM oblasts o WHERE o.katotth_code = 'UA48000000000039575';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA48040070010053688', 'Вознесенськ', 'Voznesensk'
FROM oblasts o WHERE o.katotth_code = 'UA48000000000039575';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA48040250010045068', 'Південноукраїнськ', 'Pivdennoukrainsk'
FROM oblasts o WHERE o.katotth_code = 'UA48000000000039575';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA48060150010035747', 'Миколаїв', 'Mykolaiv'
FROM oblasts o WHERE o.katotth_code = 'UA48000000000039575';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA48060210010099689', 'Нова Одеса', 'Nova Odesa'
FROM oblasts o WHERE o.katotth_code = 'UA48000000000039575';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA48060250010045389', 'Очаків', 'Ochakiv'
FROM oblasts o WHERE o.katotth_code = 'UA48000000000039575';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA48080130010068596', 'Первомайськ', 'Pervomaisk'
FROM oblasts o WHERE o.katotth_code = 'UA48000000000039575';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA51020030010083756', 'Березівка', 'Berezivka'
FROM oblasts o WHERE o.katotth_code = 'UA51000000000030770';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA51040010010048834', 'Білгород-Дністровський', 'Bilhorod-Dnistrovskyi'
FROM oblasts o WHERE o.katotth_code = 'UA51000000000030770';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA51040250010015619', 'Татарбунари', 'Tatarbunary'
FROM oblasts o WHERE o.katotth_code = 'UA51000000000030770';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA51060010010032913', 'Арциз', 'Artsyz'
FROM oblasts o WHERE o.katotth_code = 'UA51000000000030770';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA51060030010048411', 'Болград', 'Bolhrad'
FROM oblasts o WHERE o.katotth_code = 'UA51000000000030770';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA51080010010086017', 'Вилкове', 'Vylkove'
FROM oblasts o WHERE o.katotth_code = 'UA51000000000030770';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA51080030010072039', 'Ізмаїл', 'Izmail'
FROM oblasts o WHERE o.katotth_code = 'UA51000000000030770';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA51080050010036449', 'Кілія', 'Kiliia'
FROM oblasts o WHERE o.katotth_code = 'UA51000000000030770';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA51080070010065897', 'Рені', 'Reni'
FROM oblasts o WHERE o.katotth_code = 'UA51000000000030770';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA51100030010096432', 'Біляївка', 'Biliaivka'
FROM oblasts o WHERE o.katotth_code = 'UA51000000000030770';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA51100270010076757', 'Одеса', 'Odesa'
FROM oblasts o WHERE o.katotth_code = 'UA51000000000030770';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA51100310010094687', 'Теплодар', 'Teplodar'
FROM oblasts o WHERE o.katotth_code = 'UA51000000000030770';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA51100370010020298', 'Чорноморськ', 'Chornomorsk'
FROM oblasts o WHERE o.katotth_code = 'UA51000000000030770';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA51100410010044384', 'Південне', 'Pivdenne'
FROM oblasts o WHERE o.katotth_code = 'UA51000000000030770';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA51120010010049617', 'Ананьїв', 'Ananiv'
FROM oblasts o WHERE o.katotth_code = 'UA51000000000030770';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA51120030010033524', 'Балта', 'Balta'
FROM oblasts o WHERE o.katotth_code = 'UA51000000000030770';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA51120090010012317', 'Кодима', 'Kodyma'
FROM oblasts o WHERE o.katotth_code = 'UA51000000000030770';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA51120190010049331', 'Подільськ', 'Podilsk'
FROM oblasts o WHERE o.katotth_code = 'UA51000000000030770';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA51140130010040641', 'Роздільна', 'Rozdilna'
FROM oblasts o WHERE o.katotth_code = 'UA51000000000030770';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA53020010010016768', 'Глобине', 'Hlobyne'
FROM oblasts o WHERE o.katotth_code = 'UA53000000000028050';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA53020030010087471', 'Горішні Плавні', 'Horishni Plavni'
FROM oblasts o WHERE o.katotth_code = 'UA53000000000028050';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA53020110010031694', 'Кременчук', 'Kremenchuk'
FROM oblasts o WHERE o.katotth_code = 'UA53000000000028050';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA53040010010092378', 'Гребінка', 'Hrebinka'
FROM oblasts o WHERE o.katotth_code = 'UA53000000000028050';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA53040030010081016', 'Лубни', 'Lubny'
FROM oblasts o WHERE o.katotth_code = 'UA53000000000028050';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA53040090010096696', 'Пирятин', 'Pyriatyn'
FROM oblasts o WHERE o.katotth_code = 'UA53000000000028050';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA53040110010080324', 'Хорол', 'Khorol'
FROM oblasts o WHERE o.katotth_code = 'UA53000000000028050';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA53060090010040802', 'Гадяч', 'Hadiach'
FROM oblasts o WHERE o.katotth_code = 'UA53000000000028050';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA53060130010028447', 'Заводське', 'Zavodske'
FROM oblasts o WHERE o.katotth_code = 'UA53000000000028050';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA53060190010016735', 'Лохвиця', 'Lokhvytsia'
FROM oblasts o WHERE o.katotth_code = 'UA53000000000028050';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA53060230010027681', 'Миргород', 'Myrhorod'
FROM oblasts o WHERE o.katotth_code = 'UA53000000000028050';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA53080090010093569', 'Зіньків', 'Zinkiv'
FROM oblasts o WHERE o.katotth_code = 'UA53000000000028050';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA53080110010062221', 'Карлівка', 'Karlivka'
FROM oblasts o WHERE o.katotth_code = 'UA53000000000028050';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA53080130010037756', 'Кобеляки', 'Kobeliaky'
FROM oblasts o WHERE o.katotth_code = 'UA53000000000028050';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA53080370010073240', 'Полтава', 'Poltava'
FROM oblasts o WHERE o.katotth_code = 'UA53000000000028050';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA53080390010041197', 'Решетилівка', 'Reshetylivka'
FROM oblasts o WHERE o.katotth_code = 'UA53000000000028050';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA56020030010034121', 'Вараш', 'Varash'
FROM oblasts o WHERE o.katotth_code = 'UA56000000000066151';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA56040110010080334', 'Дубно', 'Dubno'
FROM oblasts o WHERE o.katotth_code = 'UA56000000000066151';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA56040290010062068', 'Радивилів', 'Radyvyliv'
FROM oblasts o WHERE o.katotth_code = 'UA56000000000066151';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA56060030010049126', 'Березне', 'Berezne'
FROM oblasts o WHERE o.katotth_code = 'UA56000000000066151';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA56060250010051586', 'Здолбунів', 'Zdolbuniv'
FROM oblasts o WHERE o.katotth_code = 'UA56000000000066151';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA56060310010035947', 'Корець', 'Korets'
FROM oblasts o WHERE o.katotth_code = 'UA56000000000066151';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA56060350010063070', 'Костопіль', 'Kostopil'
FROM oblasts o WHERE o.katotth_code = 'UA56000000000066151';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA56060450010014169', 'Острог', 'Ostroh'
FROM oblasts o WHERE o.katotth_code = 'UA56000000000066151';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA56060470010041018', 'Рівне', 'Rivne'
FROM oblasts o WHERE o.katotth_code = 'UA56000000000066151';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA56080070010011646', 'Дубровиця', 'Dubrovytsia'
FROM oblasts o WHERE o.katotth_code = 'UA56000000000066151';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA56080170010061049', 'Сарни', 'Sarny'
FROM oblasts o WHERE o.katotth_code = 'UA56000000000066151';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA59020030010075600', 'Буринь', 'Buryn'
FROM oblasts o WHERE o.katotth_code = 'UA59000000000057109';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA59020070010054283', 'Конотоп', 'Konotop'
FROM oblasts o WHERE o.katotth_code = 'UA59000000000057109';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA59020090010081204', 'Кролевець', 'Krolevets'
FROM oblasts o WHERE o.katotth_code = 'UA59000000000057109';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA59020150010023159', 'Путивль', 'Putyvl'
FROM oblasts o WHERE o.katotth_code = 'UA59000000000057109';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA59040110010017443', 'Охтирка', 'Okhtyrka'
FROM oblasts o WHERE o.katotth_code = 'UA59000000000057109';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA59040130010060037', 'Тростянець', 'Trostianets'
FROM oblasts o WHERE o.katotth_code = 'UA59000000000057109';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA59060110010062596', 'Ромни', 'Romny'
FROM oblasts o WHERE o.katotth_code = 'UA59000000000057109';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA59080030010079123', 'Білопілля', 'Bilopillia'
FROM oblasts o WHERE o.katotth_code = 'UA59000000000057109';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA59080070010055315', 'Ворожба', 'Vorozhba'
FROM oblasts o WHERE o.katotth_code = 'UA59000000000057109';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA59080110010031484', 'Лебедин', 'Lebedyn'
FROM oblasts o WHERE o.katotth_code = 'UA59000000000057109';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA59080270010036634', 'Суми', 'Sumy'
FROM oblasts o WHERE o.katotth_code = 'UA59000000000057109';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA59100030010033445', 'Глухів', 'Hlukhiv'
FROM oblasts o WHERE o.katotth_code = 'UA59000000000057109';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA59100050010097062', 'Хутір-Михайлівський', 'Khutir-Mykhailivskyi'
FROM oblasts o WHERE o.katotth_code = 'UA59000000000057109';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA59100130010040668', 'Середина-Буда', 'Seredyna-Buda'
FROM oblasts o WHERE o.katotth_code = 'UA59000000000057109';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA59100170010017917', 'Шостка', 'Shostka'
FROM oblasts o WHERE o.katotth_code = 'UA59000000000057109';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA61020070010067494', 'Кременець', 'Kremenets'
FROM oblasts o WHERE o.katotth_code = 'UA61000000000060328';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA61020090010092599', 'Ланівці', 'Lanivtsi'
FROM oblasts o WHERE o.katotth_code = 'UA61000000000060328';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA61020130010032621', 'Почаїв', 'Pochaiv'
FROM oblasts o WHERE o.katotth_code = 'UA61000000000060328';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA61020150010042611', 'Шумськ', 'Shumsk'
FROM oblasts o WHERE o.katotth_code = 'UA61000000000060328';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA61040030010016917', 'Бережани', 'Berezhany'
FROM oblasts o WHERE o.katotth_code = 'UA61000000000060328';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA61040150010018110', 'Збараж', 'Zbarazh'
FROM oblasts o WHERE o.katotth_code = 'UA61000000000060328';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA61040170010060494', 'Зборів', 'Zboriv'
FROM oblasts o WHERE o.katotth_code = 'UA61000000000060328';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA61040370010042063', 'Підгайці', 'Pidhaitsi'
FROM oblasts o WHERE o.katotth_code = 'UA61000000000060328';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA61040430010057663', 'Скалат', 'Skalat'
FROM oblasts o WHERE o.katotth_code = 'UA61000000000060328';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA61040470010037126', 'Теребовля', 'Terebovlia'
FROM oblasts o WHERE o.katotth_code = 'UA61000000000060328';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA61040490010069060', 'Тернопіль', 'Ternopil'
FROM oblasts o WHERE o.katotth_code = 'UA61000000000060328';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA61060050010030430', 'Борщів', 'Borshchiv'
FROM oblasts o WHERE o.katotth_code = 'UA61000000000060328';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA61060070010075450', 'Бучач', 'Buchach'
FROM oblasts o WHERE o.katotth_code = 'UA61000000000060328';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA61060170010057218', 'Заліщики', 'Zalishchyky'
FROM oblasts o WHERE o.katotth_code = 'UA61000000000060328';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA61060250010085416', 'Копичинці', 'Kopychyntsi'
FROM oblasts o WHERE o.katotth_code = 'UA61000000000060328';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA61060310010085741', 'Монастириська', 'Monastyryska'
FROM oblasts o WHERE o.katotth_code = 'UA61000000000060328';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA61060410010063308', 'Хоростків', 'Khorostkiv'
FROM oblasts o WHERE o.katotth_code = 'UA61000000000060328';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA61060430010047348', 'Чортків', 'Chortkiv'
FROM oblasts o WHERE o.katotth_code = 'UA61000000000060328';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA63020010010049442', 'Богодухів', 'Bohodukhiv'
FROM oblasts o WHERE o.katotth_code = 'UA63000000000041885';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA63020030010038669', 'Валки', 'Valky'
FROM oblasts o WHERE o.katotth_code = 'UA63000000000041885';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA63040010010039074', 'Балаклія', 'Balakliia'
FROM oblasts o WHERE o.katotth_code = 'UA63000000000041885';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA63040030010027594', 'Барвінкове', 'Barvinkove'
FROM oblasts o WHERE o.katotth_code = 'UA63000000000041885';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA63040090010029555', 'Ізюм', 'Izium'
FROM oblasts o WHERE o.katotth_code = 'UA63000000000041885';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA63060050010042407', 'Берестин', 'Berestyn'
FROM oblasts o WHERE o.katotth_code = 'UA63000000000041885';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA63080090010026457', 'Куп’янськ', 'Kupiansk'
FROM oblasts o WHERE o.katotth_code = 'UA63000000000041885';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA63100050010081626', 'Лозова', 'Lozova'
FROM oblasts o WHERE o.katotth_code = 'UA63000000000041885';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA63100090010068250', 'Златопіль', 'Zlatopil'
FROM oblasts o WHERE o.katotth_code = 'UA63000000000041885';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA63120070010085847', 'Дергачі', 'Derhachi'
FROM oblasts o WHERE o.katotth_code = 'UA63000000000041885';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA63120110010087291', 'Люботин', 'Liubotyn'
FROM oblasts o WHERE o.katotth_code = 'UA63000000000041885';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA63120150010020962', 'Мерефа', 'Merefa'
FROM oblasts o WHERE o.katotth_code = 'UA63000000000041885';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA63120190010022795', 'Південне', 'Pivdenne'
FROM oblasts o WHERE o.katotth_code = 'UA63000000000041885';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA63120270010096107', 'Харків', 'Kharkiv'
FROM oblasts o WHERE o.katotth_code = 'UA63000000000041885';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA63140010010035757', 'Вовчанськ', 'Vovchansk'
FROM oblasts o WHERE o.katotth_code = 'UA63000000000041885';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA63140030010017037', 'Зміїв', 'Zmiiv'
FROM oblasts o WHERE o.katotth_code = 'UA63000000000041885';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA63140110010076882', 'Слобожанське', 'Slobozhanske'
FROM oblasts o WHERE o.katotth_code = 'UA63000000000041885';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA63140170010036104', 'Чугуїв', 'Chuhuiv'
FROM oblasts o WHERE o.katotth_code = 'UA63000000000041885';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA65020010010095508', 'Берислав', 'Beryslav'
FROM oblasts o WHERE o.katotth_code = 'UA65000000000030969';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA65040010010040633', 'Генічеськ', 'Henichesk'
FROM oblasts o WHERE o.katotth_code = 'UA65000000000030969';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA65060110010021041', 'Каховка', 'Kakhovka'
FROM oblasts o WHERE o.katotth_code = 'UA65000000000030969';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA65060170010075325', 'Нова Каховка', 'Nova Kakhovka'
FROM oblasts o WHERE o.katotth_code = 'UA65000000000030969';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA65060250010044738', 'Таврійськ', 'Tavriisk'
FROM oblasts o WHERE o.katotth_code = 'UA65000000000030969';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA65080030010035864', 'Гола Пристань', 'Hola Prystan'
FROM oblasts o WHERE o.katotth_code = 'UA65000000000030969';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA65080150010023642', 'Скадовськ', 'Skadovsk'
FROM oblasts o WHERE o.katotth_code = 'UA65000000000030969';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA65100110010019482', 'Олешки', 'Oleshky'
FROM oblasts o WHERE o.katotth_code = 'UA65000000000030969';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA65100150010064384', 'Херсон', 'Kherson'
FROM oblasts o WHERE o.katotth_code = 'UA65000000000030969';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA68020050010075833', 'Дунаївці', 'Dunaivtsi'
FROM oblasts o WHERE o.katotth_code = 'UA68000000000099709';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA68020110010097898', 'Кам’янець-Подільський', 'Kamianets-Podilskyi'
FROM oblasts o WHERE o.katotth_code = 'UA68000000000099709';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA68040090010095929', 'Волочиськ', 'Volochysk'
FROM oblasts o WHERE o.katotth_code = 'UA68000000000099709';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA68040130010039416', 'Городок', 'Horodok'
FROM oblasts o WHERE o.katotth_code = 'UA68000000000099709';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA68040150010024820', 'Деражня', 'Derazhnia'
FROM oblasts o WHERE o.katotth_code = 'UA68000000000099709';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA68040210010032567', 'Красилів', 'Krasyliv'
FROM oblasts o WHERE o.katotth_code = 'UA68000000000099709';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA68040390010084208', 'Старокостянтинів', 'Starokostiantyniv'
FROM oblasts o WHERE o.katotth_code = 'UA68000000000099709';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA68040470010096613', 'Хмельницький', 'Khmelnytskyi'
FROM oblasts o WHERE o.katotth_code = 'UA68000000000099709';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA68060090010061527', 'Ізяслав', 'Iziaslav'
FROM oblasts o WHERE o.katotth_code = 'UA68000000000099709';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA68060170010043609', 'Нетішин', 'Netishyn'
FROM oblasts o WHERE o.katotth_code = 'UA68000000000099709';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA68060210010068447', 'Полонне', 'Polonne'
FROM oblasts o WHERE o.katotth_code = 'UA68000000000099709';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA68060270010040268', 'Славута', 'Slavuta'
FROM oblasts o WHERE o.katotth_code = 'UA68000000000099709';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA68060330010023704', 'Шепетівка', 'Shepetivka'
FROM oblasts o WHERE o.katotth_code = 'UA68000000000099709';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA71020030010075692', 'Багачеве', 'Bahacheve'
FROM oblasts o WHERE o.katotth_code = 'UA71000000000010357';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA71020130010081908', 'Звенигородка', 'Zvenyhorodka'
FROM oblasts o WHERE o.katotth_code = 'UA71000000000010357';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA71020290010051536', 'Тальне', 'Talne'
FROM oblasts o WHERE o.katotth_code = 'UA71000000000010357';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA71020330010098440', 'Шпола', 'Shpola'
FROM oblasts o WHERE o.katotth_code = 'UA71000000000010357';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA71040090010057400', 'Золотоноша', 'Zolotonosha'
FROM oblasts o WHERE o.katotth_code = 'UA71000000000010357';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA71060090010092249', 'Жашків', 'Zhashkiv'
FROM oblasts o WHERE o.katotth_code = 'UA71000000000010357';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA71060170010084282', 'Монастирище', 'Monastyryshche'
FROM oblasts o WHERE o.katotth_code = 'UA71000000000010357';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA71060210010010251', 'Умань', 'Uman'
FROM oblasts o WHERE o.katotth_code = 'UA71000000000010357';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA71060230010046648', 'Христинівка', 'Khrystynivka'
FROM oblasts o WHERE o.katotth_code = 'UA71000000000010357';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA71080110010037357', 'Городище', 'Horodyshche'
FROM oblasts o WHERE o.katotth_code = 'UA71000000000010357';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA71080130010022318', 'Кам’янка', 'Kamianka'
FROM oblasts o WHERE o.katotth_code = 'UA71000000000010357';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA71080150010077910', 'Канів', 'Kaniv'
FROM oblasts o WHERE o.katotth_code = 'UA71000000000010357';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA71080170010098381', 'Корсунь-Шевченківський', 'Korsun-Shevchenkivskyi'
FROM oblasts o WHERE o.katotth_code = 'UA71000000000010357';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA71080390010069946', 'Сміла', 'Smila'
FROM oblasts o WHERE o.katotth_code = 'UA71000000000010357';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA71080490010015879', 'Черкаси', 'Cherkasy'
FROM oblasts o WHERE o.katotth_code = 'UA71000000000010357';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA71080510010036826', 'Чигирин', 'Chyhyryn'
FROM oblasts o WHERE o.katotth_code = 'UA71000000000010357';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA73020070010063977', 'Вашківці', 'Vashkivtsi'
FROM oblasts o WHERE o.katotth_code = 'UA73000000000044923';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA73020090010033414', 'Вижниця', 'Vyzhnytsia'
FROM oblasts o WHERE o.katotth_code = 'UA73000000000044923';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA73040130010085979', 'Новодністровськ', 'Novodnistrovsk'
FROM oblasts o WHERE o.katotth_code = 'UA73000000000044923';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA73040170010044151', 'Сокиряни', 'Sokyriany'
FROM oblasts o WHERE o.katotth_code = 'UA73000000000044923';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA73040190010054219', 'Хотин', 'Khotyn'
FROM oblasts o WHERE o.katotth_code = 'UA73000000000044923';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA73060130010067568', 'Герца', 'Hertsa'
FROM oblasts o WHERE o.katotth_code = 'UA73000000000044923';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA73060190010067621', 'Заставна', 'Zastavna'
FROM oblasts o WHERE o.katotth_code = 'UA73000000000044923';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA73060290010095467', 'Кіцмань', 'Kitsman'
FROM oblasts o WHERE o.katotth_code = 'UA73000000000044923';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA73060410010023503', 'Новоселиця', 'Novoselytsia'
FROM oblasts o WHERE o.katotth_code = 'UA73000000000044923';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA73060490010033552', 'Сторожинець', 'Storozhynets'
FROM oblasts o WHERE o.katotth_code = 'UA73000000000044923';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA73060610010033137', 'Чернівці', 'Chernivtsi'
FROM oblasts o WHERE o.katotth_code = 'UA73000000000044923';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA74020010010096225', 'Корюківка', 'Koriukivka'
FROM oblasts o WHERE o.katotth_code = 'UA74000000000025378';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA74020030010065172', 'Мена', 'Mena'
FROM oblasts o WHERE o.katotth_code = 'UA74000000000025378';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA74020050010092446', 'Сновськ', 'Snovsk'
FROM oblasts o WHERE o.katotth_code = 'UA74000000000025378';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA74040010010021393', 'Батурин', 'Baturyn'
FROM oblasts o WHERE o.katotth_code = 'UA74000000000025378';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA74040030010089994', 'Бахмач', 'Bakhmach'
FROM oblasts o WHERE o.katotth_code = 'UA74000000000025378';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA74040050010084586', 'Бобровиця', 'Bobrovytsia'
FROM oblasts o WHERE o.katotth_code = 'UA74000000000025378';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA74040070010013105', 'Борзна', 'Borzna'
FROM oblasts o WHERE o.katotth_code = 'UA74000000000025378';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA74040250010023991', 'Ніжин', 'Nizhyn'
FROM oblasts o WHERE o.katotth_code = 'UA74000000000025378';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA74040290010030247', 'Носівка', 'Nosivka'
FROM oblasts o WHERE o.katotth_code = 'UA74000000000025378';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA74060030010060039', 'Новгород-Сіверський', 'Novhorod-Siverskyi'
FROM oblasts o WHERE o.katotth_code = 'UA74000000000025378';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA74060070010010511', 'Семенівка', 'Semenivka'
FROM oblasts o WHERE o.katotth_code = 'UA74000000000025378';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA74080030010061043', 'Ічня', 'Ichnia'
FROM oblasts o WHERE o.katotth_code = 'UA74000000000025378';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA74080130010045104', 'Прилуки', 'Pryluky'
FROM oblasts o WHERE o.katotth_code = 'UA74000000000025378';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA74100050010035827', 'Городня', 'Horodnia'
FROM oblasts o WHERE o.katotth_code = 'UA74000000000025378';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA74100310010010586', 'Остер', 'Oster'
FROM oblasts o WHERE o.katotth_code = 'UA74000000000025378';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA74100390010054825', 'Чернігів', 'Chernihiv'
FROM oblasts o WHERE o.katotth_code = 'UA74000000000025378';
INSERT INTO cities (oblast_id, katotth_code, name_uk, name_en)
SELECT o.id, 'UA80000000000093317', 'Київ', 'Kyiv'
FROM oblasts o WHERE o.katotth_code = 'UA80000000000093317';

-- ============================================================================
-- CITY_DISTRICTS (76) — category B; city_id resolved by city KATOTTH code
-- ============================================================================
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA12020010010114149', 'Амур-Нижньодніпровський', 'Amur-Nyzhnodniprovskyi'
FROM cities c WHERE c.katotth_code = 'UA12020010010037010';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA12020010010231764', 'Індустріальний', 'Industrialnyi'
FROM cities c WHERE c.katotth_code = 'UA12020010010037010';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA12020010010350200', 'Новокодацький', 'Novokodatskyi'
FROM cities c WHERE c.katotth_code = 'UA12020010010037010';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA12020010010475293', 'Самарський', 'Samarskyi'
FROM cities c WHERE c.katotth_code = 'UA12020010010037010';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA12020010010512802', 'Соборний', 'Sobornyi'
FROM cities c WHERE c.katotth_code = 'UA12020010010037010';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA12020010010639502', 'Центральний', 'Tsentralnyi'
FROM cities c WHERE c.katotth_code = 'UA12020010010037010';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA12020010010757287', 'Чечелівський', 'Chechelivskyi'
FROM cities c WHERE c.katotth_code = 'UA12020010010037010';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA12020010010816623', 'Шевченківський', 'Shevchenkivskyi'
FROM cities c WHERE c.katotth_code = 'UA12020010010037010';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA12040150010118924', 'Дніпровський', 'Dniprovskyi'
FROM cities c WHERE c.katotth_code = 'UA12040150010056523';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA12040150010213957', 'Заводський', 'Zavodskyi'
FROM cities c WHERE c.katotth_code = 'UA12040150010056523';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA12040150010395824', 'Південний', 'Pivdennyi'
FROM cities c WHERE c.katotth_code = 'UA12040150010056523';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA12060170010145934', 'Довгинцівський', 'Dovhyntsivskyi'
FROM cities c WHERE c.katotth_code = 'UA12060170010065850';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA12060170010270453', 'Інгулецький', 'Inhuletskyi'
FROM cities c WHERE c.katotth_code = 'UA12060170010065850';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA12060170010378670', 'Металургійний', 'Metalurhiinyi'
FROM cities c WHERE c.katotth_code = 'UA12060170010065850';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA12060170010439451', 'Покровський', 'Pokrovskyi'
FROM cities c WHERE c.katotth_code = 'UA12060170010065850';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA12060170010585703', 'Саксаганський', 'Saksahanskyi'
FROM cities c WHERE c.katotth_code = 'UA12060170010065850';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA12060170010643671', 'Тернівський', 'Ternivskyi'
FROM cities c WHERE c.katotth_code = 'UA12060170010065850';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA12060170010720279', 'Центрально-Міський', 'Tsentralno-Miskyi'
FROM cities c WHERE c.katotth_code = 'UA12060170010065850';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA18040190010115253', 'Богунський', 'Bohunskyi'
FROM cities c WHERE c.katotth_code = 'UA18040190010057814';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA18040190010281147', 'Корольовський', 'Korolovskyi'
FROM cities c WHERE c.katotth_code = 'UA18040190010057814';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA23060070010154443', 'Вознесенівський', 'Voznesenivskyi'
FROM cities c WHERE c.katotth_code = 'UA23060070010069526';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA23060070010228148', 'Дніпровський', 'Dniprovskyi'
FROM cities c WHERE c.katotth_code = 'UA23060070010069526';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA23060070010385728', 'Заводський', 'Zavodskyi'
FROM cities c WHERE c.katotth_code = 'UA23060070010069526';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA23060070010474202', 'Комунарський', 'Komunarskyi'
FROM cities c WHERE c.katotth_code = 'UA23060070010069526';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA23060070010595678', 'Олександрівський', 'Oleksandrivskyi'
FROM cities c WHERE c.katotth_code = 'UA23060070010069526';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA23060070010618511', 'Хортицький', 'Khortytskyi'
FROM cities c WHERE c.katotth_code = 'UA23060070010069526';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA23060070010748330', 'Шевченківський', 'Shevchenkivskyi'
FROM cities c WHERE c.katotth_code = 'UA23060070010069526';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA35040210010145346', 'Подільський', 'Podilskyi'
FROM cities c WHERE c.katotth_code = 'UA35040210010019355';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA35040210010286392', 'Фортечний', 'Fortechnyi'
FROM cities c WHERE c.katotth_code = 'UA35040210010019355';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA46060250010121390', 'Галицький', 'Halytskyi'
FROM cities c WHERE c.katotth_code = 'UA46060250010015970';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA46060250010259421', 'Залізничний', 'Zaliznychnyi'
FROM cities c WHERE c.katotth_code = 'UA46060250010015970';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA46060250010364817', 'Личаківський', 'Lychakivskyi'
FROM cities c WHERE c.katotth_code = 'UA46060250010015970';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA46060250010457177', 'Сихівський', 'Sykhivskyi'
FROM cities c WHERE c.katotth_code = 'UA46060250010015970';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA46060250010515336', 'Франківський', 'Frankivskyi'
FROM cities c WHERE c.katotth_code = 'UA46060250010015970';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA46060250010615203', 'Шевченківський', 'Shevchenkivskyi'
FROM cities c WHERE c.katotth_code = 'UA46060250010015970';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA48060150010139573', 'Заводський', 'Zavodskyi'
FROM cities c WHERE c.katotth_code = 'UA48060150010035747';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA48060150010235917', 'Інгульський', 'Inhulskyi'
FROM cities c WHERE c.katotth_code = 'UA48060150010035747';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA48060150010393291', 'Корабельний', 'Korabelnyi'
FROM cities c WHERE c.katotth_code = 'UA48060150010035747';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA48060150010443183', 'Центральний', 'Tsentralnyi'
FROM cities c WHERE c.katotth_code = 'UA48060150010035747';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA51100270010196805', 'Київський', 'Kyivskyi'
FROM cities c WHERE c.katotth_code = 'UA51100270010076757';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA51100270010275193', 'Хаджибейський', 'Khadzhybeiskyi'
FROM cities c WHERE c.katotth_code = 'UA51100270010076757';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA51100270010320268', 'Приморський', 'Prymorskyi'
FROM cities c WHERE c.katotth_code = 'UA51100270010076757';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA51100270010413116', 'Пересипський', 'Peresypskyi'
FROM cities c WHERE c.katotth_code = 'UA51100270010076757';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA53020110010112104', 'Автозаводський', 'Avtozavodskyi'
FROM cities c WHERE c.katotth_code = 'UA53020110010031694';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA53020110010228624', 'Крюківський', 'Kriukivskyi'
FROM cities c WHERE c.katotth_code = 'UA53020110010031694';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA53080370010183642', 'Київський', 'Kyivskyi'
FROM cities c WHERE c.katotth_code = 'UA53080370010073240';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA53080370010266780', 'Подільський', 'Podilskyi'
FROM cities c WHERE c.katotth_code = 'UA53080370010073240';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA53080370010339303', 'Шевченківський', 'Shevchenkivskyi'
FROM cities c WHERE c.katotth_code = 'UA53080370010073240';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA59080270010111002', 'Зарічний', 'Zarichnyi'
FROM cities c WHERE c.katotth_code = 'UA59080270010036634';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA59080270010287243', 'Ковпаківський', 'Kovpakivskyi'
FROM cities c WHERE c.katotth_code = 'UA59080270010036634';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA63120270010158723', 'Індустріальний', 'Industrialnyi'
FROM cities c WHERE c.katotth_code = 'UA63120270010096107';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA63120270010216514', 'Київський', 'Kyivskyi'
FROM cities c WHERE c.katotth_code = 'UA63120270010096107';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA63120270010315719', 'Салтівський', 'Saltivskyi'
FROM cities c WHERE c.katotth_code = 'UA63120270010096107';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA63120270010423479', 'Немишлянський', 'Nemyshlianskyi'
FROM cities c WHERE c.katotth_code = 'UA63120270010096107';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA63120270010565081', 'Новобаварський', 'Novobavarskyi'
FROM cities c WHERE c.katotth_code = 'UA63120270010096107';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA63120270010681864', 'Основ’янський', 'Osnovianskyi'
FROM cities c WHERE c.katotth_code = 'UA63120270010096107';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA63120270010736370', 'Слобідський', 'Slobidskyi'
FROM cities c WHERE c.katotth_code = 'UA63120270010096107';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA63120270010877312', 'Холодногірський', 'Kholodnohirskyi'
FROM cities c WHERE c.katotth_code = 'UA63120270010096107';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA63120270010948820', 'Шевченківський', 'Shevchenkivskyi'
FROM cities c WHERE c.katotth_code = 'UA63120270010096107';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA65100150010123057', 'Дніпровський', 'Dniprovskyi'
FROM cities c WHERE c.katotth_code = 'UA65100150010064384';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA65100150010217771', 'Корабельний', 'Korabelnyi'
FROM cities c WHERE c.katotth_code = 'UA65100150010064384';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA65100150010361097', 'Центральний', 'Tsentralnyi'
FROM cities c WHERE c.katotth_code = 'UA65100150010064384';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA71080490010144486', 'Придніпровський', 'Prydniprovskyi'
FROM cities c WHERE c.katotth_code = 'UA71080490010015879';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA71080490010259590', 'Соснівський', 'Sosnivskyi'
FROM cities c WHERE c.katotth_code = 'UA71080490010015879';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA74100390010122363', 'Деснянський', 'Desnianskyi'
FROM cities c WHERE c.katotth_code = 'UA74100390010054825';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA74100390010268220', 'Новозаводський', 'Novozavodskyi'
FROM cities c WHERE c.katotth_code = 'UA74100390010054825';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA80000000000126643', 'Голосіївський', 'Holosiivskyi'
FROM cities c WHERE c.katotth_code = 'UA80000000000093317';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA80000000000210193', 'Дарницький', 'Darnytskyi'
FROM cities c WHERE c.katotth_code = 'UA80000000000093317';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA80000000000336424', 'Деснянський', 'Desnianskyi'
FROM cities c WHERE c.katotth_code = 'UA80000000000093317';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA80000000000479391', 'Дніпровський', 'Dniprovskyi'
FROM cities c WHERE c.katotth_code = 'UA80000000000093317';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA80000000000551439', 'Оболонський', 'Obolonskyi'
FROM cities c WHERE c.katotth_code = 'UA80000000000093317';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA80000000000624772', 'Печерський', 'Pecherskyi'
FROM cities c WHERE c.katotth_code = 'UA80000000000093317';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA80000000000719633', 'Подільський', 'Podilskyi'
FROM cities c WHERE c.katotth_code = 'UA80000000000093317';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA80000000000875983', 'Святошинський', 'Sviatoshynskyi'
FROM cities c WHERE c.katotth_code = 'UA80000000000093317';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA80000000000980793', 'Солом’янський', 'Solomianskyi'
FROM cities c WHERE c.katotth_code = 'UA80000000000093317';
INSERT INTO city_districts (city_id, katotth_code, name_uk, name_en)
SELECT c.id, 'UA80000000001078669', 'Шевченківський', 'Shevchenkivskyi'
FROM cities c WHERE c.katotth_code = 'UA80000000000093317';
